languageCode = "ja-jp"
title = "#june29jp"
baseURL = "http://june29.jp/"
theme = "hugo29"

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
  description = "june29's official website"
  twitterUser = "june29"
