languageCode = "ja-jp"
title = "#june29jp"
baseURL = "https://june29.jp/"
theme = "hugo29"
rssLimit = 20

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
  description = "june29's official website"
  twitterUser = "june29"
  hatenaStarToken = "6086952ec2c380a34a31cd307d5424114a0da296"
