version: 2
jobs:
  checkout_code:
    docker:
      - image: june29/golang-hugo
    working_directory: ~/hugo
    steps:
      - checkout
      - run: |
          git submodule sync
          git submodule update --init
      - save_cache:
          key: hugo-cache
          paths:
            - ~/hugo
  build:
    docker:
      - image: june29/golang-hugo
    working_directory: ~/hugo
    steps:
      - restore_cache:
          key: hugo-cache
      - run:
          command: |
            hugo
      - save_cache:
          key: hugo-cache-public
          paths:
            - ~/hugo/public
  deploy:
    machine:
      enabled: true
    working_directory: ~/hugo/public
    steps:
      - restore_cache:
          key: hugo-cache-public
      - run:
          command: |
            git config --global user.name "${GIT_USER_NAME}"
            git config --global user.email "${GIT_USER_EMAIL}"
            git add --all
            git diff --quiet --exit-code --cached || git commit -m 'Update content [ci skip]'
            git push -f origin gh-pages
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
