version: 2
jobs:
  build:
    docker:
      - image: june29/golang-hugo
    working_directory: ~/hugo
    steps:
      - checkout
      - run:
          name: Build
          command: |
            git submodule sync
            git submodule update --init
            go run scripts/generate-entries-json.go
            hugo
      - run:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              cd public
              git init
              git checkout -b gh-pages
              git remote add origin ssh://git@github.com/june29/june29.jp
              git config --global user.name "${GIT_USER_NAME}"
              git config --global user.email "${GIT_USER_EMAIL}"
              git add --all
              git diff --quiet --exit-code --cached || git commit -m 'Update content [ci skip]'
              git push -f origin gh-pages
            fi
